### ISSUE TITLE
CoordinateConversion Widget Default Settings

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#122]
Hopefully this is an easy fix.
Currently, the CoordinateConversion Widget is displayed as a single line when clicked, like this:

![image](https://user-images.githubusercontent.com/14999738/73205429-fe4c9200-410e-11ea-837d-8827d9d1c515.png)

Is it possible to change the default display of the ConversionCoordinate Widget so that it appears like this?

![image](https://user-images.githubusercontent.com/14999738/73205497-14f2e900-410f-11ea-9eef-e930981f4b4b.png)

**Comment by shodge17** [comment]
Each of the state plane systems display their coordinates with feet as their units.  Can you 
a) allow the user to pick feet or meters, OR
b) add 3 additional coordinate options with meters as their units.
STILL low priority.  Choose a or b based on simplicity of coding

**Comment by clintonlunn** [comment]
@shodge17 for ease of coding, we should go with option B. I believe I've found the correct wkids... EPSG [2777](https://spatialreference.org/ref/epsg/2777/), [2778](https://spatialreference.org/ref/epsg/2778/), and [2779](https://spatialreference.org/ref/epsg/2779/)

**Comment by clintonlunn** [comment]
Here's a [thread](https://community.esri.com/message/909415-re-open-coordinate-conversion-widget-with-multiple-conversions-by-default-4x?commentID=909415&et=watches.email.thread#comment-909415) in the community forums asking if I can open many conversions when the widget is initially opened.

**Comment by shodge17** [comment]
This looks good.  how about changing the FEET to FT and METER to MT and then I would consider this done.

**Comment by clintonlunn** [comment]
Done, are we still contributing to the development branch or does this go into master?

**Comment by shodge17** [comment]
Dev

**Comment by shodge17** [comment]
Looks like you missed the MT ones.  after that change, update the dev and close this out.

**Comment by clintonlunn** [comment]
done, into the 'enhancements' branch
