### ISSUE TITLE
Sync zoom, highlight, and measurement on identifytask

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#167]
Coordinate the zooms, highlights, and the measurement pane (in the bottom left corner) when an identify is performed.

**Comment by clintonlunn** [comment]
measurement is now a widget so i was able to leverage that new widget. I put this into an expand widget for demonstration purposes. TODO: still need to add the identify toggle for when a user wants to also identify features within the measurement area

We initially had another measurement widget that leveraged DistanceMeasurement2D and AreaMeasurement2D widgets built into a panel. TODO: as mentioned in the commended out html need to implement a clear button. The clear measurement button in the newer measurement widget could be brought over here to fulfill that requirement.

**Comment by clintonlunn** [comment]
From email to @GeorgiannaS and @shodge17 

We did previously have this functionality in place, and is sitting in the map commented out. ArcGIS JavaScript API now has a full blown Measurement widget, but we were using some AreaMeasurement2D and DistanceMeasurement2D widgets which required more manual intervention to switch and manage state of the two to work together. I found a TODO in the html that we need to add a clearMeasurement button. That's not a hard task and has already been done in the next widget I'm about to talk about.

I began working on a new implementation of the measurement widget which includes the new combined Measurement Widget. There is a branch (https://github.com/FREAC/LABINS/tree/feature/%23167/coordinate-identify-highlight-measure) where these changes can be found.  My plan is to build out the new Measurement Widget with the integrated area/distance functionality and also include that clearMeasurement button. 

After that we can decide whether we want to put this functionality inside of an expand widget or inside of a panel (like had been done before). I can build out both and we can decide which we would like best.

**Comment by clintonlunn** [comment]
Summary of work so far:

![image](https://user-images.githubusercontent.com/24685932/102639651-5c1f0980-4127-11eb-9dff-d374825f4bc4.png)

added expand widget with distance measurement and area measurement. The bottom (i) button indicates an identify action. I enabled the user to initiate an identifytask

![image](https://user-images.githubusercontent.com/24685932/102640264-37776180-4128-11eb-966e-4fc0b677c3f4.png)

However, due to the size of my screen. (13inch macbook pro) the overview map covers up the area measurement. But, once the minimize overview task of #170 is accomplished, this won't be much of an issue anymore.

There's also a trashcan button that will destroy the measurement and identified features. I am thinking this should replace the current eraser button because it has essentially the same functionality.

@shodge17 @GeorgiannaS  There is still some cleanup to do in terms of the codebase, but could you pull this branch down and take a look please? Please let me know if I misunderstood any part of this issue and I'll get right on it. 

I went this approach instead of the previous approach (where the measuremnet widget and identify checkbox was in a panel) because I thought it looked cleaner (and the coding for it was far cleaner in my opinion). However, I can also go that approach if needed.

**Comment by clintonlunn** [comment]
Still TODO, change the expand button to one of the icons [here](https://developers.arcgis.com/javascript/latest/guide/esri-icon-font/).

**Comment by GeorgiannaS** [comment]
Clinton, I am unable to pull down from Github due to my lack of knowledge.  I am afraid that I will mess something up.

**Comment by shodge17** [comment]
Clinton
are you sure all of your code is posted?  I do not see the option to open the measure tool

**Comment by clintonlunn** [comment]
Are you looking at this branch? https://github.com/FREAC/LABINS/tree/feature/%23167/coordinate-identify-highlight-measure

I’ll be back home in about 30 minutes to take a look, but I just checked and I can see my commit that I pushed up with the measurement functionality.

**Comment by shodge17** [comment]
Ok - Found it.  did not have the one with the word -measure on the end.  I will take a look

**Comment by shodge17** [comment]
Not sure your "i" button is working.  After I measure something and try the i I still cant do an identify.  The only way to do an identify is to clear the measure.   
can you put the measurement results on the left side of the screen instead of the right?

**Comment by clintonlunn** [comment]
Can we have a call so I can see you demo it? It was working on my side.

Join Zoom Meeting
https://us04web.zoom.us/j/77010933410?pwd=ZzFBNjl0Wms4OU1JRGFPMEl4ZUQ4dz09

Meeting ID: 770 1093 3410
Passcode: X8hraw

**Comment by clintonlunn** [comment]
After meeting today, we agreed that this isn't quite done yet. We still need the following functionality:

- if we complete a measurement, allow for a click generated identify to happen
- allow for multiple measurements to happen

Also, we spoke about contacting the user to have them outline the desired functionality.

**Comment by clintonlunn** [comment]
@shodge17 for the multiple measurements functionality that we discussed on Friday, I was mistaken in saying that this functionality was already available in the widget. 

According to [this](https://community.esri.com/t5/arcgis-api-for-javascript/multiple-measurement-and-polygons/m-p/245797) post from the ArcGIS JSAPI forums, it should be possible, but we will have to code the functionality ourselves. I'm going to explore how difficult this will be to accomplish.

**Comment by clintonlunn** [comment]
@shodge17 @GeorgiannaS I was able to get the ability to identify after measurement task working, but I am continuing to struggle to be able to create multiple measurements. As I had previously said, this is not baked into the current measurement functionality and requires touching the viewModel of the measurement widget. I have been trying this but haven't found a solution just yet. 

Considering the current date and when we said this would be delivered by (12/31), could we create an issue for making these multiple measurements and roll out the current functionality?

**Comment by shodge17** [comment]
Yes - I think that is the most appropriate thing to do for now.
I say lets put in master and see what comments we get back.
thanks

**Comment by clintonlunn** [comment]
Preparing the PR now

**Comment by clintonlunn** [comment]
Initial functionality merged into master. If customer wants additional functionality, a related issue can be opened.

**Comment by clintonlunn** [comment]
Defect discovered: 

I have discovered one issue with the measure tool I would like to see if you can fix. lets say you measure something and note your value and then say I am done measuring and collapse the measurement toolbar. You will see that the measure is still active and measuring the line.
SOLUTION: When the measure toolbar is collapsed then a clearMeasurements() is issued.

**Comment by shodge17** [comment]
Just an info note:
I have spent a number of hours trying to figure out how to detect when the toolbar is collapsed with no success.  there does not seem to be an ID you can reference.  You can add an ID to the expand item, but it does not seem to be there when you look at the element level info,

**Comment by shodge17** [comment]
AHHH...  I was not familiar with the watch option.  That works exactly like I think it should.  Lets see if we get any feed back now.
